#!/usr/bin/env bash
set -euo pipefail

# Build on a Rocky/RHEL 9 host with internet access, preferably the current
# working host (for example 192.168.1.221). The target host can install the
# generated app bundle without internet access after prerequisites are ready.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${OUT_DIR:-$ROOT/dist}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
STAMP="$(date +%Y%m%d%H%M%S)"

VERSION_TEXT="$("$PYTHON_BIN" - <<'PY'
from webapp import config
print(f"{config.VERSION}-{config.PATCH_ID}")
PY
)"

BUNDLE_NAME="${BUNDLE_NAME:-webitgpt_offline_${VERSION_TEXT}_${STAMP}}"
STAGE="$OUT_DIR/$BUNDLE_NAME"
FILES_DIR="$STAGE/files"
WHEELHOUSE="$STAGE/wheelhouse"
RPMS_DIR="$STAGE/rpms"

rm -rf "$STAGE"
mkdir -p "$FILES_DIR" "$WHEELHOUSE" "$RPMS_DIR"

echo "Copying clean app files to $FILES_DIR"
if command -v rsync >/dev/null 2>&1; then
  rsync -a --delete \
    --exclude '.git/' \
    --exclude 'venv/' \
    --exclude 'data/' \
    --exclude 'logs/' \
    --exclude 'debug/logs/' \
    --exclude 'debug/reports/' \
    --exclude 'tmp/' \
    --exclude 'backup/' \
    --exclude 'dist/' \
    --exclude '.pytest_cache/' \
    --exclude '__pycache__/' \
    --exclude '*.pyc' \
    --exclude '*.pyo' \
    "$ROOT/" "$FILES_DIR/"
else
  tar \
    --exclude './.git' \
    --exclude './venv' \
    --exclude './data' \
    --exclude './logs' \
    --exclude './debug/logs' \
    --exclude './debug/reports' \
    --exclude './tmp' \
    --exclude './backup' \
    --exclude './dist' \
    --exclude './.pytest_cache' \
    --exclude './__pycache__' \
    --exclude '*/__pycache__' \
    --exclude '*.pyc' \
    --exclude '*.pyo' \
    -C "$ROOT" -cf - . | tar -C "$FILES_DIR" -xf -
fi

cp "$ROOT/scripts/install_offline.sh" "$STAGE/install_offline.sh"
cp "$ROOT/scripts/install_interactive_template.sh" "$STAGE/INSTALL.sh"
chmod +x "$STAGE/install_offline.sh" "$STAGE/INSTALL.sh"
cp "$ROOT/deploy/install.env.example" "$STAGE/install.env.example" 2>/dev/null || true

echo "Downloading Python wheels to $WHEELHOUSE"
"$PYTHON_BIN" -m pip download \
  --dest "$WHEELHOUSE" \
  --only-binary=:all: \
  -r "$ROOT/requirements.txt"

"$PYTHON_BIN" -m pip download \
  --dest "$WHEELHOUSE" \
  --only-binary=:all: \
  pip setuptools wheel

cat >"$RPMS_DIR/README.txt" <<'EOF'
This app bundle includes webitgpt source code and Python wheels only.

For a host that cannot access the internet and does not already have OS
packages or MongoDB, install the prerequisite bundle first, or use the full
offline package generated by scripts/prepare_221_full_offline_bundle.sh.
EOF

cat >"$STAGE/manifest.txt" <<EOF
Bundle: $BUNDLE_NAME
Generated at: $(date -Is)
Build host: $(hostname -f 2>/dev/null || hostname)
Root: $ROOT
Version: $VERSION_TEXT

Excluded from package:
 - data/
 - logs/
 - debug/logs/
 - debug/reports/
 - backup/
 - venv/
 - tmp/
 - dist/
 - .git/
 - Mongo dump
 - secrets / tokens / private keys

Install on target:
  tar -xzf ${BUNDLE_NAME}.tar.gz
  cd ${BUNDLE_NAME}
  sudo bash INSTALL.sh
EOF

ARCHIVE="$OUT_DIR/${BUNDLE_NAME}.tar.gz"
tar -czf "$ARCHIVE" -C "$OUT_DIR" "$BUNDLE_NAME"
echo "$ARCHIVE"
